import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WEB3 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Welcome to web3
    </div>
  );
}
